# Generated by Django 4.2 on 2025-03-19 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0004_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Bank Transfer", "Bank Transfer"),
                    ("Mobile Money", "Mobile Money"),
                    ("Credit Card", "Credit Card"),
                    ("PayPal", "PayPal"),
                    ("Cash", "Cash"),
                ],
                default="Bank Transfer",
                max_length=50,
            ),
        ),
    ]
