# Generated by Django 4.2 on 2025-03-25 08:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("customer", "0006_userprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="payment",
            name="due_date",
        ),
        migrations.AddField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025, 3, 25, 8, 17, 25, 157980, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="payment",
            name="processed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="payment",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_payments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="policyrecord",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("NOT_PAID", "Not Paid"),
                    ("PENDING", "Payment Pending"),
                    ("PAID", "Paid"),
                ],
                default="NOT_PAID",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("policy_approval", "Policy Approval"),
                    ("policy_rejection", "Policy Rejection"),
                    ("payment_due", "Payment Due"),
                    ("payment_received", "Payment Received"),
                    ("payment_rejected", "Payment Rejected"),
                    ("question_answered", "Question Answered"),
                    ("new_payment", "New Payment"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CRDB Bank", "CRDB Bank"),
                    ("NMB Bank", "NMB Bank"),
                    ("NBC Bank", "NBC Bank"),
                    ("M-Pesa", "M-Pesa"),
                    ("Tigo Pesa", "Tigo Pesa"),
                    ("Airtel Money", "Airtel Money"),
                    ("Halo Pesa", "Halo Pesa"),
                    ("Azam Pesa", "Azam Pesa"),
                ],
                default="CRDB Bank",
                max_length=50,
            ),
        ),
    ]
