# Generated by Django 4.2 on 2025-03-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0007_remove_payment_due_date_payment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="identity_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="identity_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nida", "NIDA Number"),
                    ("voter", "Voter ID Number"),
                    ("driving", "Driving License Number"),
                    ("passport", "Passport Number"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
