# Generated by Django 5.1.5 on 2025-03-18 13:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("provider", "0002_category_provider"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"verbose_name": "Category", "verbose_name_plural": "Categories"},
        ),
        migrations.AlterModelOptions(
            name="policy",
            options={"verbose_name": "Policy", "verbose_name_plural": "Policies"},
        ),
    ]
